language: go

sudo: false

matrix:
  include:
    - go: 1.7
    - go: 1.8
    - go: 1.9
    - go: 1.13.x
    - go: 1.14.x
    - go: tip
  allow_failures:
    - go: tip


script:
  - go build ./...
  - go test -v ./...